// Import necessary modules and components from Redux Toolkit
import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { Review } from "types/Review";
import { fetchReviews } from "./fetchReviews";

// Define the shape of the review state
interface ReviewState {
  reviews: Review[];
}

// Define the initial state for the review slice
const initialState: ReviewState = {
  reviews: [],
};

// Create a slice for managing reviews
export const ReviewSlice = createSlice({
  name: "reviews",
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    // Handle the fulfilled action of fetchReviews
    builder.addCase(fetchReviews.fulfilled, (state, action) => {
      state.reviews = action.payload;
    });
  },
});

// Export the reducer generated by createSlice
export const ReviewReducer = ReviewSlice.reducer;
